vich_uploader:
    db_driver: orm

    mappings:
        media_object:
            uri_prefix: '%app.path.media_object%'
            upload_destination: '%kernel.project_dir%/public%app.path.media_object%'
