easy_admin:
    entities:
        Product:
            class: App\Entity\Product
            list:
                fields:
                    - id
                    - name
                    - description
                    - price
                    - priceTax
                    - tax
                    - taxonomy
                    - { property: 'image', type: 'image', base_path: '%app.path.media_object%' }
            show:
                fields:
                    - id
                    - name
                    - description
                    - price
                    - priceTax
                    - tax
                    - taxonomy
                    - { property: 'image', type: 'image', base_path: '%app.path.media_object%' }
            form:
                fields:
                    - name
                    - description
                    - price
                    - tax
                    - taxonomy
                    - image